### PR TITLE
CMake build

### PR DESCRIPTION
**Pull request by raspine**
I've added a cmake build to the odr-dabmod.
Please see CMAKE_INSTALL for details.

### CODE REVIEW

**Comment by mpbraendli** [comment]
Hi Jörgen,

interesting development ! Can you please check with @mnhauke who already did some CMake work on ODR-DabMod about how to go forward ?

Does your CMake-based build also support the ususal dynamic linking ? I would like to avoid having two different ways to build the tool, and I'm very happy to move entirely to CMake, but I don't want to lose essential options.

Essential are for me:
 - Dynamic linking to libs
 - FFTW
 - enable/disable ZeroMQ
 - enable/disable UHD
 - enable/disable trace

Support for KISS FFT is a bit less important than the above, but of course nice to have.

Do you support these options at configure time ?

**Comment by raspine** [comment]
OK good. Right now only FFTW and UHD options are supported at configure time. Of coarse if you consider to move entirely to CMake I agree that the other options should be added. I will do so, hopefully in the coarse of next week.

**Comment by mnhauke** [comment]
@raspine 
In case you havn't seen it yet here are my unfinished WIP-versions of  ORD-Dab|Mux where i added CMake-support last year...
https://github.com/mnhauke/ODR-DabMod
https://github.com/mnhauke/ODR-DabMux

@mpbraendli 
Sorry for still not having the time to clean it up and push it upstream!
It's on my TODO and I definitly have time to finish the CMake-stuff in february this year.

**Comment by mpbraendli** [comment]
Hello,

no problem, there is no urgency about this. I would appreciate if you could coordinate on the topic, since you both started some activities. As soon as the CMakeLists can entirely replace the autotools I'll take it!

Cheers
mpb

**Comment by raspine** [comment]
@mnhauke 
OK wasn't aware about that. As you did the work on CMake for the other odr parts I don't mind if you do this one as well. Our main requirement is to have the static link options for boost and zmq. I think the best way is to merge these options into your cmake build once its ready.
I will finish of my cmake_build branch (still have some minor tweaking left) in any case as we need it now at Paneda.

**Comment by mpbraendli** [comment]
Hi all,
It is unlikey that I'm switching the ODR-mmbTools to CMake as I'm not familiar enough with it and I don't have time to switch over. Maybe in the future!
Cheers

**Comment by jsc-paneda** [comment]
OK. We will keep our cmake_build branch at Paneda updated if anyone else is interested.

**Pull request closed without merging**
